object Versions {
    const val kotlin = "1.2.61"
    const val ktor = "0.9.1"

    const val androidjob = "1.2.1"
    const val architecture = "2.0.0-rc01"
    const val arrow = "0.6.0"
    const val butterknife = "8.4.0"
    const val calligraphy = "2.1.0"
    const val constraint = "1.0.2"
    const val dagger = "2.9"
    const val dagger2 = "2.8"
    const val espresso = "3.1.0-alpha1"
    const val fakeit = "v0.7"
    const val jetpack = "0.14.2"
    const val junit = "4.12"
    const val konfig = "1.5.0.0"
    const val KotlinAndroidViewBindings = "0.12"
    const val kotlintest = "2.0.7"
    const val ktx = "1.0.0-rc02"
    const val magellan = "1.1.0"
    const val materialDialogs = "0.9.6.0"
    const val mockitoKotlin = "1.5.0"
    const val moshi = "1.6.0"
    const val multidex = "1.0.3"
    const val okhttp = "3.11.0"
    const val okio = "2.0.0"
    const val play = "11.6.2"
    const val retrofit = "2.4.0"
    const val retrofitCoroutines = "0.9.0"
    const val rxandroid = "2.0.1"
    const val rxbinding = "2.1.1"
    const val rxjava2 = "2.2.2"
    const val rxkotlin2 = "2.3.0"
    const val slimadapter = "2.1.2"
    const val support = "28.0.0-rc01"
    //    const val support = "26.1.0"
    const val timber = "4.7.1"
    const val javamoney = "1.3"
    const val coroutineVersion = "0.21.1"

}