/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val room_testing: String = "2.0.0" // up-to-date



    const val aapt2: String = "3.2.0-4818971" // available: milestone=3.3.0-alpha13-5013011

    const val android_job: String = "1.2.1" // available: milestone=1.3.0-alpha07

    const val androidx_test_runner: String = "1.1.0-alpha1" // available: milestone=1.1.0-beta01

    const val appcompat: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val browser: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val calligraphy: String = "2.1.0" // up-to-date

    const val cardview: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val com_afollestad_material_dialogs_core: String =
            "0.9.6.0" // available: milestone=2.0.0-beta3

    const val com_gradle_build_scan_gradle_plugin: String = "1.16" // up-to-date

    const val constraintlayout: String = "1.1.3" // available: milestone=2.0.0-alpha2

    const val converter_moshi: String = "2.4.0" // up-to-date

    const val core_ktx: String = "1.0.0-rc02" // available: milestone=1.0.0

    const val espresso_contrib: String = "3.1.0-alpha1" // available: milestone=3.1.0-beta01

    const val espresso_core: String = "3.1.0-alpha1" // available: milestone=3.1.0-beta01

    const val gradle: String = "3.2.0" // available: milestone=3.3.0-alpha13

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.3" // up-to-date

    const val jsr305: String = "3.0.2" // up-to-date

    const val junit: String = "4.12" // up-to-date

    const val kotlin_android_extensions: String = "1.2.71" // up-to-date

    const val kotlin_annotation_processing_gradle: String = "1.2.71" // up-to-date

    const val kotlin_coroutines_retrofit: String = "0.9.0" // available: milestone=0.12.0

    const val kotlin_gradle_plugin: String = "1.2.71" // up-to-date

    const val kotlin_reflect: String = "1.2.71" // up-to-date

    const val kotlin_scripting_compiler_embeddable: String = "1.2.71" // up-to-date

    const val kotlin_stdlib: String = "1.2.71" // up-to-date

    const val kotlin_stdlib_jdk8: String = "1.2.71" // up-to-date

    const val kotlinandroidviewbindings: String = "0.12" // up-to-date

    const val kotlintest: String = "2.0.7" // up-to-date

    const val ktor_features: String = "0.9.1" // available: milestone=1.0.0-alpha-1

    const val ktor_server_core: String = "0.9.1" // available: milestone=1.0.0-alpha-1

    const val ktor_server_netty: String = "0.9.1" // available: milestone=1.0.0-alpha-1

    const val legacy_support_v4: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val lint_gradle: String = "26.2.0" // available: milestone=26.3.0-alpha13

    const val logging_interceptor: String = "3.11.0" // up-to-date

    const val magellan: String = "1.1.0" // up-to-date

    const val magellan_rx: String = "1.1.0" // up-to-date

    const val magellan_support: String = "1.1.0" // up-to-date

    const val material: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val mediarouter: String = "1.0.0-alpha1" // available: milestone=1.0.0

    const val mockito_kotlin: String = "1.5.0" // up-to-date

    const val mockwebserver: String = "3.11.0" // up-to-date

    const val moneta_bp: String = "1.3" // up-to-date

    const val moshi: String = "1.6.0" // available: milestone=1.7.0

    const val multidex: String = "2.0.0" // up-to-date

    const val okhttp: String = "3.11.0" // up-to-date

    const val okio: String = "2.0.0" // available: milestone=2.1.0

    const val percentlayout: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val preference: String = "1.0.0-rc01" // available: milestone=1.0.0

    const val retrofit: String = "2.4.0" // up-to-date

    const val retrofit2_rxjava2_adapter: String = "1.0.0" // up-to-date

    const val retrofit_mock: String = "2.4.0" // up-to-date

    const val room_compiler: String = "2.0.0" // available: milestone=2.1.0-alpha01

    const val room_runtime: String = "2.0.0" // available: milestone=2.1.0-alpha01

    const val room_rxjava2: String = "2.0.0" // available: milestone=2.1.0-alpha01

    const val rxandroid: String = "2.0.1" // up-to-date

    const val rxbinding_kotlin: String = "2.1.1" // available: milestone=2.2.0

    const val rxbinding_support_v4_kotlin: String = "2.1.1" // available: milestone=2.2.0

    const val rxjava: String = "2.2.2" // up-to-date

    const val rxkotlin: String = "2.3.0" // up-to-date

    const val rxpermissions: String = "0.9.5" // up-to-date

    const val slimadapter: String = "2.1.2" // up-to-date

    const val timber: String = "4.7.1" // up-to-date

    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.0-20181008235842+0000"

        const val releaseCandidate: String = ""
    }
}
